; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=m68k-linux -verify-machineinstrs | FileCheck %s

define zeroext i8 @test1(i8 zeroext %a) nounwind {
; CHECK-LABEL: test1:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    cmpi.b #34, (7,%sp)
; CHECK-NEXT:    ble .LBB0_2
; CHECK-NEXT:  ; %bb.1:
; CHECK-NEXT:    moveq #10, %d0
; CHECK-NEXT:    rts
; CHECK-NEXT:  .LBB0_2:
; CHECK-NEXT:    moveq #20, %d0
; CHECK-NEXT:    rts
  %bool = icmp sge i8 %a, 35
  %res = select i1 %bool, i8 10, i8 20
  ret i8 %res
}

define zeroext i16 @test2(i16 zeroext %a) nounwind {
; CHECK-LABEL: test2:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    move.w (6,%sp), %d0
; CHECK-NEXT:    cmpi.w #34, %d0
; CHECK-NEXT:    ble .LBB1_2
; CHECK-NEXT:  ; %bb.1:
; CHECK-NEXT:    moveq #2, %d1
; CHECK-NEXT:    bra .LBB1_3
; CHECK-NEXT:  .LBB1_2:
; CHECK-NEXT:    moveq #5, %d1
; CHECK-NEXT:  .LBB1_3:
; CHECK-NEXT:    muls %d1, %d0
; CHECK-NEXT:    cmpi.w #44, %d0
; CHECK-NEXT:    ble .LBB1_5
; CHECK-NEXT:  ; %bb.4:
; CHECK-NEXT:    moveq #10, %d0
; CHECK-NEXT:    rts
; CHECK-NEXT:  .LBB1_5:
; CHECK-NEXT:    moveq #20, %d0
; CHECK-NEXT:    rts
  %bool = icmp sge i16 %a, 35
  %da = mul i16 2, %a
  %ta = mul i16 5, %a
  %res = select i1 %bool, i16 %da, i16 %ta
  %bool2 = icmp sge i16 %res, 45
  %res2 = select i1 %bool2, i16 10, i16 20
  ret i16 %res2
}
