; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=m68k-linux -verify-machineinstrs | FileCheck %s

define i64 @test1(i64 %a, i64 %b) nounwind {
; CHECK-LABEL: test1:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    suba.l #4, %sp
; CHECK-NEXT:    movem.l %d2, (0,%sp) ; 8-byte Folded Spill
; CHECK-NEXT:    move.l (8,%sp), %d2
; CHECK-NEXT:    move.l (16,%sp), %d0
; CHECK-NEXT:    move.l (12,%sp), %d1
; CHECK-NEXT:    add.l (20,%sp), %d1
; CHECK-NEXT:    addx.l %d2, %d0
; CHECK-NEXT:    movem.l (0,%sp), %d2 ; 8-byte Folded Reload
; CHECK-NEXT:    adda.l #4, %sp
; CHECK-NEXT:    rts
  %res = add i64 %a, %b
  ret i64 %res
}
